### ISSUE TITLE
PolymerElement / element-element: Wrong file location for platform.min.js

### ISSUE THREAD

**Issue by cosmicdreams** [googlearchive/projects#18]
in projects/PolymerElement/element-element, there is an incorrect file location for the included platform.min.js that breaks the code example.  The broken example only properly displays the <hr> and nothing else.

I recommend that you correct the file location to:

``` html
<script src="../../../platform/platform.js"></script>
```

This will properly include an existing file AND give the user a working demo without requiring them run npm install on the repository then run grunt to generate the proper platform.min.js file.

**Comment by sjmiles** [comment]
This project is deprecated and superseded by the latest Polymer code. It's only in the repo for purposes of archaeology.

**Comment by cosmicdreams** [comment]
That makes sense, I was just about to add a comment here about document.extendHTMLPrototype was also breaking the example.  I'm looking to pull some great examples to demo WC to developers who have never seen it before, do you have time to recommend a handful of your favorite demos (in project/ or labs/) on G+? 
https://plus.google.com/106029910359400047659

**Comment by cosmicdreams** [comment]
@sjmiles you might want to add a comment to the example that it's depreciated or better yet, remove it from the repo.  Let the git history handle the archaeology.

**Comment by sjmiles** [comment]
@cosmicdreams, absolutely you are right, but this is the tip of the iceberg. We will have to do a big cleanup step when we have a chance (sooner rather than later).
