### ISSUE TITLE
Sandbox banner should disappear

### ISSUE THREAD

**Issue by singhalpriyank** [googlearchive/projects#20]
The Sandbox banner should disappear after a few seconds and not show up again for the user on page reload unless cookies are cleared.

**Comment by jkomoros** [comment]
Correction: the banner should only appear the first time you load the page
(unless cookies are cleared). No need for it to disappear while the user is
on the page.

**Comment by dfreedm** [comment]
Fixed in 9a38f0446fe0712cb4bf8f477670e6c494c1de04
