### ISSUE TITLE
Move each component into its own repo

### ISSUE THREAD

**Issue by zenorocha** [googlearchive/projects#23]
Hey guys,

I'm the creator of [customelements.io](http://customelements.io/), which is a gallery for Web Components and we're registering components per Github repo.

We would love to feature Polymer's projects, but they are all in the same repo. So I was wondering, why not keeping each component in a separated repo and include them here via Git Submodules, just like [Brick](https://github.com/mozilla/brick/tree/master/component) does?

**Comment by sjmiles** [comment]
This is an important topic and I think it deserves robust discussion.

I think the best place to do that would be polymer-dev@googlegroups.com. How do you feel about that? Would you mind starting a thread there?

The immediate answer is that we have (at my count) 73 components collectively in the libraries, and that is just the beginning. Managing 73 separate repositories just sounds like a lot of work. I could be totally wrong about that, that's part of why we want to wrestle with this question.
